### ISSUE TITLE
Need help in attending PyCon 2023

### ISSUE THREAD

**Issue by yell0wc0w3** [pyladies/info#60]
[](url)Hello,

My name is Hoang, CTO and cofounder of Mely.ai, based on Montreal Canada.  We have our data scientist, Laurie, who would like to attend the Pycon conference, but we are working on a local grant here in Montreal to make it happen.

The grant needs a signature from a host incubator organization that will help with the soft-landing of the participant at Salt Lake City.  There’s no financial commitment on your side aside from assisting Laurie at PyCon, if required.  

Would PyLadies be able to assist in getting us the grant to go to PyCon?  I’m attaching the template from MITACS for the host organization.

Thanks, 
[MEI_Letter_of_Acknowledgment_International_Host_Incubator.pdf](https://github.com/pyladies/info/files/10899104/MEI_Letter_of_Acknowledgment_International_Host_Incubator.pdf)

**Comment by Mariatta** [comment]
Hi @yell0wc0w3 , thanks for the interest in PyCon.
I think this is something the PyCon team may be able to help with instead of the PyLadies group.

Can you please write to pycon-reg@python.org regarding this matter?  Additionally, can you also clarify of what kind of help will be needed by PyCon staff?

Thank you.
